# NYC dinner events from Luma

Luma's official API (`api.lu.ma/public/v1`, used with a `luma-api-...` key) only manages **your own** calendar — it has no city-wide discovery.

Instead we use the public discovery endpoint the luma.com website itself calls (no auth needed):
`GET https://api.lu.ma/discover/get-paginated-events`

It accepts a geographic bounding box (`north`/`south`/`east`/`west`), which returns **every public upcoming event** in that area, paginated via `pagination_cursor`. We pull the whole NYC box (~850 events), then filter for dinners.

In [1]:
import time
import requests

DISCOVER_URL = "https://api.lu.ma/discover/get-paginated-events"
HEADERS = {"User-Agent": "Mozilla/5.0"}

# Bounding box covering all five NYC boroughs
NYC_BBOX = {"north": 40.92, "south": 40.49, "west": -74.26, "east": -73.70}


def fetch_all_events(extra_params=None, max_pages=100, delay=0.15):
    """Paginate through the Luma discovery feed and return all event dicts."""
    events, cursor = [], None
    for _ in range(max_pages):
        params = {"pagination_limit": 50, **NYC_BBOX, **(extra_params or {})}
        if cursor:
            params["pagination_cursor"] = cursor
        resp = requests.get(DISCOVER_URL, params=params, headers=HEADERS, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        events.extend(entry["event"] for entry in data["entries"])
        if not data.get("has_more"):
            break
        cursor = data["next_cursor"]
        time.sleep(delay)  # be polite to their servers
    return events


all_events = fetch_all_events()
print(f"Fetched {len(all_events)} upcoming public events in NYC")

Fetched 851 upcoming public events in NYC

In [2]:
import pandas as pd

DINNER_KEYWORDS = ("dinner", "supper", "tasting menu", "omakase", "chef's table")


def to_row(e):
    geo = e.get("geo_address_info") or {}
    return {
        "name": e["name"],
        "start": pd.Timestamp(e["start_at"]).tz_convert(e.get("timezone", "America/New_York")),
        "neighborhood": geo.get("sublocality") or geo.get("city"),
        "address": geo.get("full_address"),
        "url": f"https://luma.com/{e['url']}",
    }


dinners = [e for e in all_events if any(k in e["name"].lower() for k in DINNER_KEYWORDS)]
df = pd.DataFrame(to_row(e) for e in dinners).sort_values("start").reset_index(drop=True)

df.to_csv("nyc_dinners.csv", index=False)
print(f"{len(df)} dinner events — saved to nyc_dinners.csv")
df

41 dinner events — saved to nyc_dinners.csv

,name,start,neighborhood,address,url
0,MDS 9 Michelin Dinner July 2026,2026-07-18 17:45:00-04:00,Koreatown,NaN,https://luma.com/MDS9DinnerJuly2026
1,NYC Female Founders Dinner,2026-07-18 18:00:00-04:00,West Village,"Mino Brasserie, 225 W 12th St, New York, NY 10...",https://luma.com/vk8q58sr
2,Max AI Private Practice Advisory Board (Dinner),2026-07-18 18:30:00-04:00,Midtown West,NaN,https://luma.com/s26-adboard-dinner-aad
3,Sunset Supper with Chef Jacob Nguyen,2026-07-19 18:00:00-04:00,Greenwood Heights,"Brooklyn Grange @ Sunset Park, 850 3rd Ave Roo...",https://luma.com/w0eyebmm
4,Women Founders Dinner: Summer Rooftop Series,2026-07-19 18:30:00-04:00,Midtown West,NaN,https://luma.com/connnext-pkqe
5,Chelsea Community Dinner,2026-07-20 18:30:00-04:00,Chelsea,"Neighbor, 176 9th Ave, New York, NY 10011, USA",https://luma.com/lf77sjoe
6,BRIDGES: Executive Summit Welcome Dinner spons...,2026-07-20 19:30:00-04:00,West Village,"L'Artusi Supper Club, 105 Christopher St, New ...",https://luma.com/41f9dg3v
7,AI Founders Supper Club (Hosted by The AI Furn...,2026-07-21 18:00:00-04:00,NoMad,NaN,https://luma.com/xxrgfwv6
8,Supper Club 033,2026-07-21 20:00:00-04:00,Chinatown,NaN,https://luma.com/zw0a0sa9
9,"Solarpunk, Communes, & Co-Living Dinner Series...",2026-07-22 18:00:00-04:00,Fort Greene,NaN,https://luma.com/82mt3j7y
10,Sierra's NYC Summer Dinner,2026-07-22 18:00:00-04:00,South Village,"Emily, 35 Downing St, New York, NY 10014, USA",https://luma.com/6mwwvki4
11,Linkup NYC dinner #3,2026-07-22 18:30:00-04:00,Manhattan,"1 Oliver St, New York, NY 10038, USA",https://luma.com/x73vahde
12,CyberCEO Executive Briefing & Dinner: ROI-Posi...,2026-07-23 18:30:00-04:00,Midtown East,NaN,https://luma.com/cybers-0p50
13,"Finance Leader Dinner with PwC, Vayu, Abacum &...",2026-07-23 18:30:00-04:00,Midtown East,"Empire Steak House East, 151 E 50th St, New Yo...",https://luma.com/n1w191tg
14,ZavoVentures: Bridging Startup Founders and In...,2026-07-23 18:30:00-04:00,Manhattan,NaN,https://luma.com/cxpei3z0
15,Ăn Xôi Pop Up Dinner,2026-07-23 19:00:00-04:00,Flatiron District,"NeueHouse Madison Square, 110 E 25th St, New Y...",https://luma.com/anxoiatneuehouse
16,The Dinner Table at Grandma's Home (Flatiron),2026-07-23 19:00:00-04:00,Flatiron District,"Grandma's Home 外婆家, 56 W 22nd St, New York, NY...",https://luma.com/DinnerTableGrandmasHome1
17,NYC CISO Dinner,2026-07-23 19:00:00-04:00,Theater District,NaN,https://luma.com/niznoiws
18,Whop x Rain Founders Dinner,2026-07-23 19:00:00-04:00,NoMad,NaN,https://luma.com/oavskysa
19,Just Indonesian Dinner by Jason Soekarno,2026-07-24 19:30:00-04:00,Gowanus,"304 Bond St, Brooklyn, NY 11231, USA",https://luma.com/dinnerjul24
20,Just Korean Dinner by Jisoo Choi,2026-07-26 17:00:00-04:00,Manhattan,"393 Broadway 5th floor, New York, NY 10013, USA",https://luma.com/dinnerjul26
21,Junto Founder Dinner (Hosted by Andrew & Friends),2026-07-28 18:00:00-04:00,East Village,NaN,https://luma.com/juntodinnerjuly
22,Junto Founder Dinner (Hosted by Andrew & Friends),2026-07-29 18:00:00-04:00,NoMad,NaN,https://luma.com/juntodinnerjuly29
23,Malu Journey Dinner: The Connect Experience,2026-07-29 18:30:00-04:00,NoMad,NaN,https://luma.com/jvh06n7u
24,"Agentic AI, Unfiltered - New York City Executi...",2026-07-30 18:00:00-04:00,Midtown South,"Ramerino - Italian Prime Restaurant, 16 E 39th...",https://luma.com/gtvlrr8l
25,StartupExperts NYC: Summer Community Dinner,2026-08-05 19:00:00-04:00,Midtown Manhattan,"Jade Rabbit, 32 W 48th St Rooftop, New York, N...",https://luma.com/summer-community-dinner
26,The Dinner Table at Le Petit Village: A 50+ Di...,2026-08-05 19:00:00-04:00,New York,"Le Petit Village, 173 7th Ave S, New York, NY ...",https://luma.com/DinnerTableLePetitVillage2
27,The Arab Table | Musly Private Members Dinner ...,2026-08-06 19:00:00-04:00,Midtown South,"Pera Mediterranean Brasserie, 303 Madison Ave,...",https://luma.com/1bwckl4m
28,Just Vegetables Dinner by Sam Ong,2026-08-07 19:30:00-04:00,Gowanus,"304 Bond St, Brooklyn, NY 11231, USA",https://luma.com/xl0bhmzm
29,Literary Dinner with André Aciman and Sarah Ma...,2026-08-10 18:30:00-04:00,South Village,"Sullaluna, 41 Carmine St, New York, NY 10014, USA",https://luma.com/cllzfcm3
30,Executive Dinner: Leveraging AI Agents,2026-08-11 19:00:00-04:00,Theater District,NaN,https://luma.com/newyork-dinner
31,🇺🇸 Michelin‑Invest Dinner🥂🕯 Family Offices Inv...,2026-08-13 18:00:00-04:00,Midtown Manhattan,"711 5th Ave, New York, NY 10022, USA",https://luma.com/3tfefikz
32,"Just Friends Dinner by Ruth Lee, Irvan Torbett...",2026-08-14 19:30:00-04:00,Gowanus,"304 Bond St, Brooklyn, NY 11231, USA",https://luma.com/hi0x0gzd
33,MáLà Project x Odd One In Present: The Spicies...,2026-08-15 12:30:00-04:00,Greenpoint,"MáLà Project Greenpoint, 603 Manhattan Ave, Br...",https://luma.com/3qd2ff20
34,Bengali-American Health & Wellness Dinner Series,2026-08-15 15:00:00-04:00,Jackson Heights,NaN,https://luma.com/qzykdrpi
35,Girlies in Tech Dinner pt. 11 <3 | NYC Edition...,2026-09-02 19:00:00-04:00,NoMad,NaN,https://luma.com/i3whlzeq
36,Funded Founder IP Law Dinner,2026-09-03 19:00:00-04:00,Midtown South,"Fushimi Times Square, 311 W 43rd St, New York,...",https://luma.com/earlystageip
37,Just Dinner,2026-09-11 19:30:00-04:00,Gowanus,"304 Bond St, Brooklyn, NY 11231, USA",https://luma.com/zb9vlfsd
38,Sunset Supper with Chef Alfredo Ravelo,2026-09-13 18:00:00-04:00,Greenwood Heights,"Brooklyn Grange @ Sunset Park, 850 3rd Ave Roo...",https://luma.com/2ot6k1y9
39,Just Middle Eastern Dinner by Carla Aziz,2026-09-18 19:30:00-04:00,Gowanus,"304 Bond St, Brooklyn, NY 11231, USA",https://luma.com/csmfl2vk
40,"Private Upstate Founders Dinner: NYC, Climate ...",2026-09-23 17:30:00-04:00,Bowery,NaN,https://luma.com/lli6upfa

## Guest lists — everything Luma exposes publicly

**Emails are not obtainable.** They exist only in `GET /event/get-guest-list`, which requires being **signed in as the host or a registered guest**. That's private by design — there is no public endpoint, profile field, or query param that returns an attendee's email, so we don't attempt it. (The code below keeps an `email` column, but it stays empty — it's there to make that explicit.)

Everything a guest *chose* to make public **is** available, embedded in each event page's `__NEXT_DATA__` JSON under `featured_guests`. Per guest, the full public field set is:

- **Identity:** name, first/last name, `username`, short bio, avatar image, verified badge, timezone
- **Contact / social:** LinkedIn, Twitter/X, Instagram, TikTok, YouTube, personal website — whichever handles they added
- **Profile meta** (from `luma.com/user/<id>`): join date, #events attended, #events hosted

Caveats:
- `featured_guests` is capped at **10 names** even when more registered, and only appears when the host enabled "show guest list" (17 of our 41 dinners). Hidden lists expose nothing.
- Handles are self-entered, so some are blank, wrong, or junk.

In [3]:
import json
import re

NEXT_DATA_RE = re.compile(
    r'__NEXT_DATA__" type="application/json">(.*?)</script>', re.S
)


def fetch_event_page(slug):
    """Return the embedded event-detail JSON from a public Luma event page."""
    resp = requests.get(f"https://luma.com/{slug}", headers=HEADERS, timeout=30)
    resp.raise_for_status()
    match = NEXT_DATA_RE.search(resp.text)
    return json.loads(match.group(1))["props"]["pageProps"]["initialData"]["data"]


def guest_names(person_list):
    return [p.get("name") or f"{p.get('first_name','')} {p.get('last_name','')}".strip()
            for p in (person_list or [])]


def social_url(kind, handle):
    """Turn a self-entered handle into a full profile URL (best effort)."""
    if not handle:
        return None
    h = str(handle).strip().lstrip("@")
    if h.startswith("http"):
        return h
    if kind == "linkedin":   # stored as a path like "/in/jane" or bare "jane"
        return "https://www.linkedin.com" + (h if h.startswith("/") else "/in/" + h)
    if kind == "twitter":
        return "https://x.com/" + h.lstrip("/")
    if kind == "instagram":
        return "https://instagram.com/" + h.lstrip("/")
    if kind == "tiktok":
        return "https://tiktok.com/@" + h.lstrip("/@")
    if kind == "youtube":
        return "https://youtube.com/@" + h.lstrip("/@")
    if kind == "website":
        return "https://" + h
    return h


def guest_record(g, event_name, event_url):
    """All publicly available fields for one guest."""
    return {
        "event": event_name,
        "event_url": event_url,
        "guest": g.get("name"),
        "first_name": g.get("first_name"),
        "last_name": g.get("last_name"),
        "username": g.get("username"),
        "bio": g.get("bio_short"),
        "verified": g.get("is_verified"),
        "timezone": g.get("timezone"),
        "email": None,  # never exposed publicly by Luma — requires host login
        "linkedin": social_url("linkedin", g.get("linkedin_handle")),
        "twitter": social_url("twitter", g.get("twitter_handle")),
        "instagram": social_url("instagram", g.get("instagram_handle")),
        "tiktok": social_url("tiktok", g.get("tiktok_handle")),
        "youtube": social_url("youtube", g.get("youtube_handle")),
        "website": social_url("website", g.get("website")),
        "avatar_url": g.get("avatar_url"),
        "luma_profile": f"https://luma.com/user/{g['api_id']}" if g.get("api_id") else None,
        "api_id": g.get("api_id"),
    }


guest_rows = []       # one row per (event, guest) — the full public roster
enriched = []         # one row per dinner — counts + host/guest summary

for e in dinners:
    slug = e["url"]
    event_url = f"https://luma.com/{slug}"
    try:
        data = fetch_event_page(slug)
    except Exception as err:
        print(f"skip {slug}: {err}")
        continue

    featured = data.get("featured_guests") or []
    enriched.append({
        "name": e["name"],
        "start": pd.Timestamp(e["start_at"]).tz_convert(e.get("timezone", "America/New_York")),
        "guest_count": data.get("guest_count") or 0,
        "guests_shown": len(featured),          # host reveals at most 10 publicly
        "hosts": ", ".join(guest_names(data.get("hosts"))),
        "featured_guests": ", ".join(guest_names(featured)),
        "url": event_url,
    })

    # hosts are public people too — capture them, tagged as role
    for h in (data.get("hosts") or []):
        rec = guest_record(h, e["name"], event_url)
        rec["role"] = "host"
        guest_rows.append(rec)
    for g in featured:
        rec = guest_record(g, e["name"], event_url)
        rec["role"] = "guest"
        guest_rows.append(rec)

    time.sleep(0.3)  # be polite

dinners_with_guests = pd.DataFrame(enriched).sort_values("start").reset_index(drop=True)
print(f"Enriched {len(dinners_with_guests)} dinners; "
      f"{sum(dinners_with_guests['guests_shown'] > 0)} expose a public guest list")
dinners_with_guests

Enriched 41 dinners; 17 expose a public guest list

,name,start,guest_count,guests_shown,hosts,featured_guests,url
0,MDS 9 Michelin Dinner July 2026,2026-07-18 17:45:00-04:00,0,0,"Million Dollar Sellers (MDS), Eugene Khayman",,https://luma.com/MDS9DinnerJuly2026
1,NYC Female Founders Dinner,2026-07-18 18:00:00-04:00,6,6,X26 - xMcKinsey Entrepreneurs Community,"Alina Vrsaljko, Laura Gallagher, Anna Muszkiew...",https://luma.com/vk8q58sr
2,Max AI Private Practice Advisory Board (Dinner),2026-07-18 18:30:00-04:00,0,0,"Zubair Ahsan, Enea Gjoka, Andrew H Weinstein, ...",,https://luma.com/s26-adboard-dinner-aad
3,Sunset Supper with Chef Jacob Nguyen,2026-07-19 18:00:00-04:00,11,10,Brooklyn Grange,"Michael Benowitz, Jenn Sherman, Katie McGarry,...",https://luma.com/w0eyebmm
4,Women Founders Dinner: Summer Rooftop Series,2026-07-19 18:30:00-04:00,0,0,Celia Davis,,https://luma.com/connnext-pkqe
5,Chelsea Community Dinner,2026-07-20 18:30:00-04:00,5,5,Neighbor,"Mei Tong, Kathleen Ledvora, Franziska Ibscher,...",https://luma.com/lf77sjoe
6,BRIDGES: Executive Summit Welcome Dinner spons...,2026-07-20 19:30:00-04:00,0,0,"Helen Joel, Jennifer Jiao, Neil Daiksel, Katie...",,https://luma.com/41f9dg3v
7,AI Founders Supper Club (Hosted by The AI Furn...,2026-07-21 18:00:00-04:00,0,0,"Angela Mascarenas (The AI Furnace), Hamza Zave...",,https://luma.com/xxrgfwv6
8,Supper Club 033,2026-07-21 20:00:00-04:00,12,10,Nicholas Rhodes,"Megan O'Neill, Jen Toth, Kate Bancroft, Beth F...",https://luma.com/zw0a0sa9
9,"Solarpunk, Communes, & Co-Living Dinner Series...",2026-07-22 18:00:00-04:00,13,10,Chris Morello,"Gillian Morris, Beau, Matt Pfeiffer, Amber, Ja...",https://luma.com/82mt3j7y
10,Sierra's NYC Summer Dinner,2026-07-22 18:00:00-04:00,0,0,"Edith, Anay, Conan",,https://luma.com/6mwwvki4
11,Linkup NYC dinner #3,2026-07-22 18:30:00-04:00,11,10,"Valentin sauvaire, Stephanie Song","Ayaan Naveed Malik, Michael Louis, Eve Halimi,...",https://luma.com/x73vahde
12,CyberCEO Executive Briefing & Dinner: ROI-Posi...,2026-07-23 18:30:00-04:00,11,10,"Nicole L, David Algava, Auberry Drljic, Gianna...","Yoni Shohet, Christian Almenar, Shay Shwartz, ...",https://luma.com/cybers-0p50
13,"Finance Leader Dinner with PwC, Vayu, Abacum &...",2026-07-23 18:30:00-04:00,33,10,"Vayu Events, Erez Agmon, Tyanna, Christina Whi...","Andrew Lobo, Erez Agmon, adelina pepenella, Ad...",https://luma.com/n1w191tg
14,ZavoVentures: Bridging Startup Founders and In...,2026-07-23 18:30:00-04:00,70,10,"Liana Zavo, Inbal Weiss, Chen Shir, Christina ...","Kathryn Kushner, Ivan Alexey Osipov, marina sh...",https://luma.com/cxpei3z0
15,Ăn Xôi Pop Up Dinner,2026-07-23 19:00:00-04:00,0,0,"NeueHouse Productions, An Xoi",,https://luma.com/anxoiatneuehouse
16,The Dinner Table at Grandma's Home (Flatiron),2026-07-23 19:00:00-04:00,15,10,The Dinner Table Club,"Radheshri Oza, Amber De Vos, Roman F, Monica L...",https://luma.com/DinnerTableGrandmasHome1
17,NYC CISO Dinner,2026-07-23 19:00:00-04:00,0,0,"Akul Gupta, Brandon Veiseh, Dean",,https://luma.com/niznoiws
18,Whop x Rain Founders Dinner,2026-07-23 19:00:00-04:00,0,0,"Bear @ Whop, Rain Events",,https://luma.com/oavskysa
19,Just Indonesian Dinner by Jason Soekarno,2026-07-24 19:30:00-04:00,0,0,Studio Bumi,,https://luma.com/dinnerjul24
20,Just Korean Dinner by Jisoo Choi,2026-07-26 17:00:00-04:00,0,0,"Studio Bumi, Jisoo Choi",,https://luma.com/dinnerjul26
21,Junto Founder Dinner (Hosted by Andrew & Friends),2026-07-28 18:00:00-04:00,0,0,Andrew Yeung,,https://luma.com/juntodinnerjuly
22,Junto Founder Dinner (Hosted by Andrew & Friends),2026-07-29 18:00:00-04:00,0,0,Andrew Yeung,,https://luma.com/juntodinnerjuly29
23,Malu Journey Dinner: The Connect Experience,2026-07-29 18:30:00-04:00,12,10,"Vanessa Johnson, Kara Glassman, Melissa Ng","Lori, Sofia B. Pertuz, PhD, PCC, Deb Serri, El...",https://luma.com/jvh06n7u
24,"Agentic AI, Unfiltered - New York City Executi...",2026-07-30 18:00:00-04:00,0,0,"Kei, Chris",,https://luma.com/gtvlrr8l
25,StartupExperts NYC: Summer Community Dinner,2026-08-05 19:00:00-04:00,0,0,"StartupExperts, Tim Frazier",,https://luma.com/summer-community-dinner
26,The Dinner Table at Le Petit Village: A 50+ Di...,2026-08-05 19:00:00-04:00,10,10,The Dinner Table Club,"Doshka Harvey, Andrew Sole, Nancy Tarantola, M...",https://luma.com/DinnerTableLePetitVillage2
27,The Arab Table | Musly Private Members Dinner ...,2026-08-06 19:00:00-04:00,0,0,Musly Team,,https://luma.com/1bwckl4m
28,Just Vegetables Dinner by Sam Ong,2026-08-07 19:30:00-04:00,0,0,"Studio Bumi, Sam Ong",,https://luma.com/xl0bhmzm
29,Literary Dinner with André Aciman and Sarah Ma...,2026-08-10 18:30:00-04:00,0,0,Lit Club NYC,,https://luma.com/cllzfcm3
30,Executive Dinner: Leveraging AI Agents,2026-08-11 19:00:00-04:00,0,0,"Ramón Muchacho (Stack AI), Justin Munro",,https://luma.com/newyork-dinner
31,🇺🇸 Michelin‑Invest Dinner🥂🕯 Family Offices Inv...,2026-08-13 18:00:00-04:00,4,4,"💓𝖒𝖆𝖓𝖆𝖓𝖆 fois.fyi 🔜 xShares, Perps Capital, fam...","Jordan Bronstein, Nicolas, Ramadan A, Ramadan ...",https://luma.com/3tfefikz
32,"Just Friends Dinner by Ruth Lee, Irvan Torbett...",2026-08-14 19:30:00-04:00,0,0,Studio Bumi,,https://luma.com/hi0x0gzd
33,MáLà Project x Odd One In Present: The Spicies...,2026-08-15 12:30:00-04:00,0,0,"Julie Zhu, leilei, Gloria Liu",,https://luma.com/3qd2ff20
34,Bengali-American Health & Wellness Dinner Series,2026-08-15 15:00:00-04:00,74,10,"Dr. Mishal Reja, Narin Ahmed","Zaima Alam, IMRUL KABIR, Rizwan Ahmed, Nabila ...",https://luma.com/qzykdrpi
35,Girlies in Tech Dinner pt. 11 <3 | NYC Edition...,2026-09-02 19:00:00-04:00,0,0,Jordyn Harrison,,https://luma.com/i3whlzeq
36,Funded Founder IP Law Dinner,2026-09-03 19:00:00-04:00,4,4,Stephen Michael,"Emily, Fatima Ashraf, Rohan Agarwal, Ali Gurocak",https://luma.com/earlystageip
37,Just Dinner,2026-09-11 19:30:00-04:00,0,0,Studio Bumi,,https://luma.com/zb9vlfsd
38,Sunset Supper with Chef Alfredo Ravelo,2026-09-13 18:00:00-04:00,9,9,Brooklyn Grange,"Brooklyn Grange Events, Celine Chan, Shannon L...",https://luma.com/2ot6k1y9
39,Just Middle Eastern Dinner by Carla Aziz,2026-09-18 19:30:00-04:00,0,0,"Studio Bumi, Carla A",,https://luma.com/csmfl2vk
40,"Private Upstate Founders Dinner: NYC, Climate ...",2026-09-23 17:30:00-04:00,5,5,"Olivia Goldstein, Hailee Greene","Mike Ma, Ulrik Soderstrom, Dallas Gilpin , Jon...",https://luma.com/lli6upfa

In [4]:
# The flattened public roster: one row per (event, person) with every public field
guests = pd.DataFrame(guest_rows)

# Reorder so identity + contact columns lead
cols = ["event", "role", "guest", "first_name", "last_name", "username", "bio",
        "verified", "email", "linkedin", "twitter", "instagram", "tiktok",
        "youtube", "website", "timezone", "avatar_url", "luma_profile",
        "api_id", "event_url"]
guests = guests[[c for c in cols if c in guests.columns]]

dinners_with_guests.to_csv("nyc_dinners_with_guests.csv", index=False)
guests.to_csv("nyc_dinner_guests.csv", index=False)

# How much contact info did we actually get?
has = lambda c: guests[c].notna().sum()
print(f"{len(guests)} people ({(guests['role']=='guest').sum()} guests, "
      f"{(guests['role']=='host').sum()} hosts) across {guests['event'].nunique()} dinners")
print(f"  LinkedIn: {has('linkedin')}   Twitter: {has('twitter')}   "
      f"Instagram: {has('instagram')}   Website: {has('website')}   "
      f"Email: {has('email')} (never public)")
guests.head(20)

227 people (143 guests, 84 hosts) across 40 dinners
  LinkedIn: 130   Twitter: 50   Instagram: 73   Website: 29   Email: 0 (never public)

,event,role,guest,first_name,last_name,username,bio,verified,email,linkedin,twitter,instagram,tiktok,youtube,website,timezone,avatar_url,luma_profile,api_id,event_url
0,MDS 9 Michelin Dinner July 2026,host,Million Dollar Sellers (MDS),Million Dollar Sellers,(MDS),eventsMDS,,False,None,https://www.linkedin.com/company/million-dolla...,https://x.com/mdsonly,https://instagram.com/mdsonly,NaN,https://youtube.com/@milliondollarsellers,https://www.mds.co/,America/Mexico_City,https://images.lumacdn.com/avatars/te/4b2c760c...,https://luma.com/user/usr-4kIUfqrIcO1SwSi,usr-4kIUfqrIcO1SwSi,https://luma.com/MDS9DinnerJuly2026
1,MDS 9 Michelin Dinner July 2026,host,Eugene Khayman,Eugene,Khayman,NaN,,False,None,https://www.linkedin.com/in/million-dollar-sel...,https://x.com/mdsonly,https://instagram.com/mdsonly,NaN,https://youtube.com/@milliondollarsellers,https://mds.co,America/New_York,https://images.lumacdn.com/avatars/g4/af5ed74c...,https://luma.com/user/usr-BoHFbmDK0J9K0sb,usr-BoHFbmDK0J9K0sb,https://luma.com/MDS9DinnerJuly2026
2,NYC Female Founders Dinner,host,X26 - xMcKinsey Entrepreneurs Community,Reece,Griffiths,x26,NaN,False,None,NaN,NaN,NaN,NaN,NaN,NaN,Africa/Johannesburg,https://cdn.lu.ma/avatars/ii/2c86b2c4-5656-445...,https://luma.com/user/usr-FiFJOwIZdOo9BNR,usr-FiFJOwIZdOo9BNR,https://luma.com/vk8q58sr
3,NYC Female Founders Dinner,guest,Alina Vrsaljko,Alina,Vrsaljko,NaN,NaN,False,None,https://www.linkedin.com/in/alina-vrsaljko,https://x.com/Brooklyn,NaN,NaN,NaN,NaN,America/Los_Angeles,https://cdn.lu.ma/avatars-default/avatar_2.png,https://luma.com/user/usr-3S7DQTYHyqfkpMf,usr-3S7DQTYHyqfkpMf,https://luma.com/vk8q58sr
4,NYC Female Founders Dinner,guest,Laura Gallagher,Laura,Gallagher,NaN,NaN,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_15.png,https://luma.com/user/usr-7Pm8Kl29goo6fVm,usr-7Pm8Kl29goo6fVm,https://luma.com/vk8q58sr
5,NYC Female Founders Dinner,guest,Anna Muszkiewicz,NaN,NaN,NaN,NaN,False,None,https://www.linkedin.com/in/anna-muszkiewicz-p...,NaN,NaN,NaN,NaN,NaN,Asia/Kolkata,https://cdn.lu.ma/avatars-default/avatar_15.png,https://luma.com/user/usr-B0Nat0CpoWP0lYq,usr-B0Nat0CpoWP0lYq,https://luma.com/vk8q58sr
6,NYC Female Founders Dinner,guest,Tina Yuan,Tina,Yuan,NaN,NaN,False,None,https://www.linkedin.com/in/tinayuan8,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_22.png,https://luma.com/user/usr-eOJpHQq5NaQxAdO,usr-eOJpHQq5NaQxAdO,https://luma.com/vk8q58sr
7,NYC Female Founders Dinner,guest,Sophie Jewsbury,Sophie,Jewsbury,NaN,,False,None,https://www.linkedin.com/in/sophiejewsbury,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_2.png,https://luma.com/user/usr-FlwPN5XlJRX6Q0t,usr-FlwPN5XlJRX6Q0t,https://luma.com/vk8q58sr
8,NYC Female Founders Dinner,guest,Iness Arabi,Iness,Arabi,NaN,NaN,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_42.png,https://luma.com/user/usr-xiYVy9eYrRwz5cV,usr-xiYVy9eYrRwz5cV,https://luma.com/vk8q58sr
9,Max AI Private Practice Advisory Board (Dinner),host,Zubair Ahsan,Zubair,Ahsan,zubairahsan,,False,None,https://www.linkedin.com/in/zubairahsan,NaN,https://instagram.com/zubairahsan,NaN,NaN,NaN,America/New_York,https://images.lumacdn.com/avatars/pr/6e0ca7d1...,https://luma.com/user/usr-YLVi5IiVl0Zxaq1,usr-YLVi5IiVl0Zxaq1,https://luma.com/s26-adboard-dinner-aad
10,Max AI Private Practice Advisory Board (Dinner),host,Enea Gjoka,Enea,Gjoka,NaN,,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/Denver,https://cdn.lu.ma/avatars-default/avatar_42.png,https://luma.com/user/usr-eN2G7Df4b5DFC1Y,usr-eN2G7Df4b5DFC1Y,https://luma.com/s26-adboard-dinner-aad
11,Max AI Private Practice Advisory Board (Dinner),host,Andrew H Weinstein,Andrew,Weinstein,NaN,NaN,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_34.png,https://luma.com/user/usr-a79r0bqwFYFg3ux,usr-a79r0bqwFYFg3ux,https://luma.com/s26-adboard-dinner-aad
12,Max AI Private Practice Advisory Board (Dinner),host,Tyler Menge,Tyler,Menge,NaN,NaN,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_41.png,https://luma.com/user/usr-4vAsCyjTnGTRaB0,usr-4vAsCyjTnGTRaB0,https://luma.com/s26-adboard-dinner-aad
13,Sunset Supper with Chef Jacob Nguyen,host,Brooklyn Grange,Brooklyn,Grange,brooklyngrange,NaN,False,None,NaN,NaN,https://instagram.com/brooklyngrange,NaN,NaN,NaN,America/New_York,https://images.lumacdn.com/uploads/0j/d3eab42f...,https://luma.com/user/usr-s9S2pBZs3QKEoSZ,usr-s9S2pBZs3QKEoSZ,https://luma.com/w0eyebmm
14,Sunset Supper with Chef Jacob Nguyen,guest,Michael Benowitz,Michael,Benowitz,NaN,NaN,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_2.png,https://luma.com/user/usr-cdUyFLPtTwUs91X,usr-cdUyFLPtTwUs91X,https://luma.com/w0eyebmm
15,Sunset Supper with Chef Jacob Nguyen,guest,Jenn Sherman,Jennifer,Sherman,NaN,,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_35.png,https://luma.com/user/usr-f9DjIH9XfTu6Evc,usr-f9DjIH9XfTu6Evc,https://luma.com/w0eyebmm
16,Sunset Supper with Chef Jacob Nguyen,guest,Katie McGarry,Katie,McGarry,NaN,NaN,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_22.png,https://luma.com/user/usr-GUluQtmmWA4Gfbj,usr-GUluQtmmWA4Gfbj,https://luma.com/w0eyebmm
17,Sunset Supper with Chef Jacob Nguyen,guest,Caroline De Diego,Caroline,De Diego,NaN,,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_23.png,https://luma.com/user/usr-MkN5poFxYPc23NN,usr-MkN5poFxYPc23NN,https://luma.com/w0eyebmm
18,Sunset Supper with Chef Jacob Nguyen,guest,Eric McCord-Snook,Eric,McCord-Snook,NaN,,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://images.lumacdn.com/uploads/zk/f84f88d1...,https://luma.com/user/usr-Nd1Awk8Wh3Cfo5J,usr-Nd1Awk8Wh3Cfo5J,https://luma.com/w0eyebmm
19,Sunset Supper with Chef Jacob Nguyen,guest,Menen Missailidis,Menen,Missailidis,NaN,NaN,False,None,NaN,NaN,NaN,NaN,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_13.png,https://luma.com/user/usr-r8REJBECIlGf94g,usr-r8REJBECIlGf94g,https://luma.com/w0eyebmm

In [5]:
# Optional: enrich each unique person with profile-page meta
# (join date, #events attended, #events hosted). One extra request per person.
FETCH_PROFILE_META = True


def fetch_profile(api_id):
    resp = requests.get(f"https://luma.com/user/{api_id}", headers=HEADERS, timeout=30)
    resp.raise_for_status()
    match = NEXT_DATA_RE.search(resp.text)
    return json.loads(match.group(1))["props"]["pageProps"]["initialData"]


if FETCH_PROFILE_META:
    meta = {}
    ids = [a for a in guests["api_id"].dropna().unique()]
    for i, api_id in enumerate(ids, 1):
        try:
            d = fetch_profile(api_id)
            meta[api_id] = {
                "joined_at": d.get("joined_at"),
                "events_attended": d.get("event_attended_count"),
                "events_hosted": d.get("event_hosted_count"),
            }
        except Exception as err:
            print(f"skip {api_id}: {err}")
        time.sleep(0.25)
    meta_df = pd.DataFrame.from_dict(meta, orient="index")
    guests = guests.merge(meta_df, left_on="api_id", right_index=True, how="left")
    guests.to_csv("nyc_dinner_guests.csv", index=False)
    print(f"Added profile meta for {len(meta)} unique people")

guests.head(20)

Added profile meta for 214 unique people

,event,role,guest,first_name,last_name,username,bio,verified,email,linkedin,...,youtube,website,timezone,avatar_url,luma_profile,api_id,event_url,joined_at,events_attended,events_hosted
0,MDS 9 Michelin Dinner July 2026,host,Million Dollar Sellers (MDS),Million Dollar Sellers,(MDS),eventsMDS,,False,None,https://www.linkedin.com/company/million-dolla...,...,https://youtube.com/@milliondollarsellers,https://www.mds.co/,America/Mexico_City,https://images.lumacdn.com/avatars/te/4b2c760c...,https://luma.com/user/usr-4kIUfqrIcO1SwSi,usr-4kIUfqrIcO1SwSi,https://luma.com/MDS9DinnerJuly2026,2025-05-07T22:45:22.607Z,3,128
1,MDS 9 Michelin Dinner July 2026,host,Eugene Khayman,Eugene,Khayman,NaN,,False,None,https://www.linkedin.com/in/million-dollar-sel...,...,https://youtube.com/@milliondollarsellers,https://mds.co,America/New_York,https://images.lumacdn.com/avatars/g4/af5ed74c...,https://luma.com/user/usr-BoHFbmDK0J9K0sb,usr-BoHFbmDK0J9K0sb,https://luma.com/MDS9DinnerJuly2026,2025-04-01T13:45:19.145Z,30,53
2,NYC Female Founders Dinner,host,X26 - xMcKinsey Entrepreneurs Community,Reece,Griffiths,x26,NaN,False,None,NaN,...,NaN,NaN,Africa/Johannesburg,https://cdn.lu.ma/avatars/ii/2c86b2c4-5656-445...,https://luma.com/user/usr-FiFJOwIZdOo9BNR,usr-FiFJOwIZdOo9BNR,https://luma.com/vk8q58sr,2023-01-11T12:05:37.578Z,3,41
3,NYC Female Founders Dinner,guest,Alina Vrsaljko,Alina,Vrsaljko,NaN,NaN,False,None,https://www.linkedin.com/in/alina-vrsaljko,...,NaN,NaN,America/Los_Angeles,https://cdn.lu.ma/avatars-default/avatar_2.png,https://luma.com/user/usr-3S7DQTYHyqfkpMf,usr-3S7DQTYHyqfkpMf,https://luma.com/vk8q58sr,2025-10-15T14:07:24.607Z,169,2
4,NYC Female Founders Dinner,guest,Laura Gallagher,Laura,Gallagher,NaN,NaN,False,None,NaN,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_15.png,https://luma.com/user/usr-7Pm8Kl29goo6fVm,usr-7Pm8Kl29goo6fVm,https://luma.com/vk8q58sr,2026-03-28T17:35:01.028Z,3,0
5,NYC Female Founders Dinner,guest,Anna Muszkiewicz,NaN,NaN,NaN,NaN,False,None,https://www.linkedin.com/in/anna-muszkiewicz-p...,...,NaN,NaN,Asia/Kolkata,https://cdn.lu.ma/avatars-default/avatar_15.png,https://luma.com/user/usr-B0Nat0CpoWP0lYq,usr-B0Nat0CpoWP0lYq,https://luma.com/vk8q58sr,2024-09-12T01:20:29.694Z,4,0
6,NYC Female Founders Dinner,guest,Tina Yuan,Tina,Yuan,NaN,NaN,False,None,https://www.linkedin.com/in/tinayuan8,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_22.png,https://luma.com/user/usr-eOJpHQq5NaQxAdO,usr-eOJpHQq5NaQxAdO,https://luma.com/vk8q58sr,2025-09-24T16:37:19.936Z,12,0
7,NYC Female Founders Dinner,guest,Sophie Jewsbury,Sophie,Jewsbury,NaN,,False,None,https://www.linkedin.com/in/sophiejewsbury,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_2.png,https://luma.com/user/usr-FlwPN5XlJRX6Q0t,usr-FlwPN5XlJRX6Q0t,https://luma.com/vk8q58sr,2024-09-06T22:44:44.184Z,81,1
8,NYC Female Founders Dinner,guest,Iness Arabi,Iness,Arabi,NaN,NaN,False,None,NaN,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_42.png,https://luma.com/user/usr-xiYVy9eYrRwz5cV,usr-xiYVy9eYrRwz5cV,https://luma.com/vk8q58sr,2026-06-09T13:47:04.101Z,4,0
9,Max AI Private Practice Advisory Board (Dinner),host,Zubair Ahsan,Zubair,Ahsan,zubairahsan,,False,None,https://www.linkedin.com/in/zubairahsan,...,NaN,NaN,America/New_York,https://images.lumacdn.com/avatars/pr/6e0ca7d1...,https://luma.com/user/usr-YLVi5IiVl0Zxaq1,usr-YLVi5IiVl0Zxaq1,https://luma.com/s26-adboard-dinner-aad,2020-10-20T05:09:05.559Z,8,14
10,Max AI Private Practice Advisory Board (Dinner),host,Enea Gjoka,Enea,Gjoka,NaN,,False,None,NaN,...,NaN,NaN,America/Denver,https://cdn.lu.ma/avatars-default/avatar_42.png,https://luma.com/user/usr-eN2G7Df4b5DFC1Y,usr-eN2G7Df4b5DFC1Y,https://luma.com/s26-adboard-dinner-aad,2026-03-08T02:20:00.545Z,1,13
11,Max AI Private Practice Advisory Board (Dinner),host,Andrew H Weinstein,Andrew,Weinstein,NaN,NaN,False,None,NaN,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_34.png,https://luma.com/user/usr-a79r0bqwFYFg3ux,usr-a79r0bqwFYFg3ux,https://luma.com/s26-adboard-dinner-aad,2026-02-18T19:42:17.424Z,4,5
12,Max AI Private Practice Advisory Board (Dinner),host,Tyler Menge,Tyler,Menge,NaN,NaN,False,None,NaN,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_41.png,https://luma.com/user/usr-4vAsCyjTnGTRaB0,usr-4vAsCyjTnGTRaB0,https://luma.com/s26-adboard-dinner-aad,2026-03-28T03:25:53.065Z,2,3
13,Sunset Supper with Chef Jacob Nguyen,host,Brooklyn Grange,Brooklyn,Grange,brooklyngrange,NaN,False,None,NaN,...,NaN,NaN,America/New_York,https://images.lumacdn.com/uploads/0j/d3eab42f...,https://luma.com/user/usr-s9S2pBZs3QKEoSZ,usr-s9S2pBZs3QKEoSZ,https://luma.com/w0eyebmm,2026-05-09T15:38:01.167Z,1,117
14,Sunset Supper with Chef Jacob Nguyen,guest,Michael Benowitz,Michael,Benowitz,NaN,NaN,False,None,NaN,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_2.png,https://luma.com/user/usr-cdUyFLPtTwUs91X,usr-cdUyFLPtTwUs91X,https://luma.com/w0eyebmm,2026-06-23T00:30:38.784Z,1,0
15,Sunset Supper with Chef Jacob Nguyen,guest,Jenn Sherman,Jennifer,Sherman,NaN,,False,None,NaN,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_35.png,https://luma.com/user/usr-f9DjIH9XfTu6Evc,usr-f9DjIH9XfTu6Evc,https://luma.com/w0eyebmm,2024-11-06T21:50:40.470Z,6,0
16,Sunset Supper with Chef Jacob Nguyen,guest,Katie McGarry,Katie,McGarry,NaN,NaN,False,None,NaN,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_22.png,https://luma.com/user/usr-GUluQtmmWA4Gfbj,usr-GUluQtmmWA4Gfbj,https://luma.com/w0eyebmm,2026-06-04T15:21:24.143Z,1,0
17,Sunset Supper with Chef Jacob Nguyen,guest,Caroline De Diego,Caroline,De Diego,NaN,,False,None,NaN,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_23.png,https://luma.com/user/usr-MkN5poFxYPc23NN,usr-MkN5poFxYPc23NN,https://luma.com/w0eyebmm,2026-05-08T14:57:49.828Z,3,0
18,Sunset Supper with Chef Jacob Nguyen,guest,Eric McCord-Snook,Eric,McCord-Snook,NaN,,False,None,NaN,...,NaN,NaN,America/New_York,https://images.lumacdn.com/uploads/zk/f84f88d1...,https://luma.com/user/usr-Nd1Awk8Wh3Cfo5J,usr-Nd1Awk8Wh3Cfo5J,https://luma.com/w0eyebmm,2026-06-25T01:46:09.798Z,1,0
19,Sunset Supper with Chef Jacob Nguyen,guest,Menen Missailidis,Menen,Missailidis,NaN,NaN,False,None,NaN,...,NaN,NaN,America/New_York,https://cdn.lu.ma/avatars-default/avatar_13.png,https://luma.com/user/usr-r8REJBECIlGf94g,usr-r8REJBECIlGf94g,https://luma.com/w0eyebmm,2025-09-23T02:06:26.838Z,2,0